backend_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('XYZ-Hotel/', include("index.urls")),
    path('XYZ-Hotel/guests/', include("guests.urls")),
]

guests/urls.py
from django.urls import path, include
from .views import executive1, executive2, executive3, executive4, deluxe1, deluxe2, deluxe3, deluxe4, standard1, standard2, standard3, standard4,active, record

app_name = "guests"

#my urls

urlpatterns= [
    path("", record, name="recordsview"),
    path("deluxe1/", deluxe1, name="deluxe1view"),
    path("deluxe2/", deluxe2, name="deluxe2view"),
    path("deluxe3/", deluxe3, name="deluxe3view"),
    path("deluxe4/", deluxe4, name="deluxe4view"),
    path("standard1/", standard1, name="standard1view"),
    path("standard2/", standard2, name="standard2view"),
    path("standard3/", standard3, name="standard3view"),
    path("standard4/", standard4, name="standard4view"),
    path("execute1/", executive1, name="executive1view"),
    path("execute2/", executive2, name="executive2view"),
    path("execute3/", executive3, name="executive3view"),
    path("execute4/", executive4, name="executive4view"),
    path("active/", active, name="activeguestsview")
]

index/urls.py
from django.urls import path, include
from .views import index_page, about, contact, services, rooms, manage_room

#My urls and their views
app_name = "index"

urlpatterns = [
    path("", index_page, name="homeview"),
    path("about/", about, name="aboutview"),
    path("contact/", contact, name="contactview"),
    path("service/", services, name='serviceview'),
    #path("rooms/", rooms, name='roomsview'),
    path("manage_room/", manage_room, name='manageview'),
    
]

guests/models.py
from django.db import models

# My model
class Guest(models.Model):
    Name = models.CharField(max_length=100)
    Email = models.EmailField(max_length=10000)
    Occupation = models.CharField(max_length=10000)
    Room_Category = models.CharField(max_length=100)
    Room_Type = models.CharField(max_length=100)
    Room_Number = models.IntegerField()
    Amount_Paid = models.CharField(max_length=100)
    Number_of_Nights = models.IntegerField()
    Start_Date = models.DateField()
    End_Date = models.DateField()
    

    def __str__(self):
        return self.Name

guests/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from .models import Guest


#My views
def deluxe1(request):
    if request.method == "POST":
        name = request.POST.get("Name")
        email = request.POST.get("Email")
        occupation = request.POST.get("Occupation")
        roomcategory = request.POST.get("Room_Category")
        roomtype = request.POST.get("Room_Type")
        roomnumber = request.POST.get("Room_Number")
        amount = request.POST.get("Amount_Paid")
        nights = request.POST.get("Number_of_Nights")
        start = request.POST.get("Start_Date")
        end = request.POST.get("End_Date")
        new_guest = Guest(Name=name, Email=email, Occupation=occupation, Room_Category=roomcategory, Room_Type=roomtype, Room_Number=roomnumber, Amount_Paid=amount, Number_of_Nights=nights, Start_Date=start, End_Date=end)
        new_guest.save()
        return redirect("guests:recordsview")
    return render(request, "guests/deluxeguest1.html")

def deluxe2(request):
    if request.method == "POST":
        name = request.POST.get("Name")
        email = request.POST.get("Email")
        occupation = request.POST.get("Occupation")
        roomcategory = request.POST.get("Room_Category")
        roomtype = request.POST.get("Room_Type")
        roomnumber = request.POST.get("Room_Number")
        amount = request.POST.get("Amount_Paid")
        nights = request.POST.get("Number_of_Nights")
        start = request.POST.get("Start_Date")
        end = request.POST.get("End_Date")
        new_guest = Guest(Name=name, Email=email, Occupation=occupation, Room_Category=roomcategory, Room_Type=roomtype, Room_Number=roomnumber, Amount_Paid=amount, Number_of_Nights=nights, Start_Date=start, End_Date=end)
        new_guest.save()
        return redirect("guests:recordsview")
    return render(request, "guests/deluxeguest2.html")

def deluxe3(request):
    if request.method == "POST":
        name = request.POST.get("Name")
        email = request.POST.get("Email")
        occupation = request.POST.get("Occupation")
        roomcategory = request.POST.get("Room_Category")
        roomtype = request.POST.get("Room_Type")
        roomnumber = request.POST.get("Room_Number")
        amount = request.POST.get("Amount_Paid")
        nights = request.POST.get("Number_of_Nights")
        start = request.POST.get("Start_Date")
        end = request.POST.get("End_Date")
        new_guest = Guest(Name=name, Email=email, Occupation=occupation, Room_Category=roomcategory, Room_Type=roomtype, Room_Number=roomnumber, Amount_Paid=amount, Number_of_Nights=nights, Start_Date=start, End_Date=end)
        new_guest.save()
        return redirect("guests:recordsview")
    return render(request, "guests/deluxeguest3.html")

def deluxe4(request):
    if request.method == "POST":
        name = request.POST.get("Name")
        email = request.POST.get("Email")
        occupation = request.POST.get("Occupation")
        roomcategory = request.POST.get("Room_Category")
        roomtype = request.POST.get("Room_Type")
        roomnumber = request.POST.get("Room_Number")
        amount = request.POST.get("Amount_Paid")
        nights = request.POST.get("Number_of_Nights")
        start = request.POST.get("Start_Date")
        end = request.POST.get("End_Date")
        new_guest = Guest(Name=name, Email=email, Occupation=occupation, Room_Category=roomcategory, Room_Type=roomtype, Room_Number=roomnumber, Amount_Paid=amount, Number_of_Nights=nights, Start_Date=start, End_Date=end)
        new_guest.save()
        return redirect("guests:recordsview")
    return render(request, "guests/deluxeguest4.html")

def executive1(request):
    if request.method == "POST":
        name = request.POST.get("Name")
        email = request.POST.get("Email")
        occupation = request.POST.get("Occupation")
        roomcategory = request.POST.get("Room_Category")
        roomtype = request.POST.get("Room_Type")
        roomnumber = request.POST.get("Room_Number")
        amount = request.POST.get("Amount_Paid")
        nights = request.POST.get("Number_of_Nights")
        start = request.POST.get("Start_Date")
        end = request.POST.get("End_Date")
        new_guest = Guest(Name=name, Email=email, Occupation=occupation, Room_Category=roomcategory, Room_Type=roomtype, Room_Number=roomnumber, Amount_Paid=amount, Number_of_Nights=nights, Start_Date=start, End_Date=end)
        new_guest.save()
        return redirect("guests:recordsview")
    return render(request, "guests/executiveguest1.html")

def executive2(request):
    if request.method == "POST":
        name = request.POST.get("Name")
        email = request.POST.get("Email")
        occupation = request.POST.get("Occupation")
        roomcategory = request.POST.get("Room_Category")
        roomtype = request.POST.get("Room_Type")
        roomnumber = request.POST.get("Room_Number")
        amount = request.POST.get("Amount_Paid")
        nights = request.POST.get("Number_of_Nights")
        start = request.POST.get("Start_Date")
        end = request.POST.get("End_Date")
        new_guest = Guest(Name=name, Email=email, Occupation=occupation, Room_Category=roomcategory, Room_Type=roomtype, Room_Number=roomnumber, Amount_Paid=amount, Number_of_Nights=nights, Start_Date=start, End_Date=end)
        new_guest.save()
        return redirect("guests:recordsview")
    return render(request, "guests/executiveguest2.html")

def executive3(request):
    if request.method == "POST":
        name = request.POST.get("Name")
        email = request.POST.get("Email")
        occupation = request.POST.get("Occupation")
        roomcategory = request.POST.get("Room_Category")
        roomtype = request.POST.get("Room_Type")
        roomnumber = request.POST.get("Room_Number")
        amount = request.POST.get("Amount_Paid")
        nights = request.POST.get("Number_of_Nights")
        start = request.POST.get("Start_Date")
        end = request.POST.get("End_Date")
        new_guest = Guest(Name=name, Email=email, Occupation=occupation, Room_Category=roomcategory, Room_Type=roomtype, Room_Number=roomnumber, Amount_Paid=amount, Number_of_Nights=nights, Start_Date=start, End_Date=end)
        new_guest.save()
        return redirect("guests:recordsview")
    return render(request, "guests/executiveguest3.html")

def executive4(request):
    if request.method == "POST":
        name = request.POST.get("Name")
        email = request.POST.get("Email")
        occupation = request.POST.get("Occupation")
        roomcategory = request.POST.get("Room_Category")
        roomtype = request.POST.get("Room_Type")
        roomnumber = request.POST.get("Room_Number")
        amount = request.POST.get("Amount_Paid")
        nights = request.POST.get("Number_of_Nights")
        start = request.POST.get("Start_Date")
        end = request.POST.get("End_Date")
        new_guest = Guest(Name=name, Email=email, Occupation=occupation, Room_Category=roomcategory, Room_Type=roomtype, Room_Number=roomnumber, Amount_Paid=amount, Number_of_Nights=nights, Start_Date=start, End_Date=end)
        new_guest.save()
        return redirect("guests:recordsview")
    return render(request, "guests/executiveguest4.html")

def standard1(request):
    if request.method == "POST":
        name = request.POST.get("Name")
        email = request.POST.get("Email")
        occupation = request.POST.get("Occupation")
        roomcategory = request.POST.get("Room_Category")
        roomtype = request.POST.get("Room_Type")
        roomnumber = request.POST.get("Room_Number")
        amount = request.POST.get("Amount_Paid")
        nights = request.POST.get("Number_of_Nights")
        start = request.POST.get("Start_Date")
        end = request.POST.get("End_Date")
        new_guest = Guest(Name=name, Email=email, Occupation=occupation, Room_Category=roomcategory, Room_Type=roomtype, Room_Number=roomnumber, Amount_Paid=amount, Number_of_Nights=nights, Start_Date=start, End_Date=end)
        new_guest.save()
        return redirect("guests:recordsview")
    return render(request, "guests/standardguest1.html")

def standard2(request):
    if request.method == "POST":
        name = request.POST.get("Name")
        email = request.POST.get("Email")
        occupation = request.POST.get("Occupation")
        roomcategory = request.POST.get("Room_Category")
        roomtype = request.POST.get("Room_Type")
        roomnumber = request.POST.get("Room_Number")
        amount = request.POST.get("Amount_Paid")
        nights = request.POST.get("Number_of_Nights")
        start = request.POST.get("Start_Date")
        end = request.POST.get("End_Date")
        new_guest = Guest(Name=name, Email=email, Occupation=occupation, Room_Category=roomcategory, Room_Type=roomtype, Room_Number=roomnumber, Amount_Paid=amount, Number_of_Nights=nights, Start_Date=start, End_Date=end)
        new_guest.save()
        return redirect("guests:recordsview")
    return render(request, "guests/standardguest2.html")

def standard3(request):
    if request.method == "POST":
        name = request.POST.get("Name")
        email = request.POST.get("Email")
        occupation = request.POST.get("Occupation")
        roomcategory = request.POST.get("Room_Category")
        roomtype = request.POST.get("Room_Type")
        roomnumber = request.POST.get("Room_Number")
        amount = request.POST.get("Amount_Paid")
        nights = request.POST.get("Number_of_Nights")
        start = request.POST.get("Start_Date")
        end = request.POST.get("End_Date")
        new_guest = Guest(Name=name, Email=email, Occupation=occupation, Room_Category=roomcategory, Room_Type=roomtype, Room_Number=roomnumber, Amount_Paid=amount, Number_of_Nights=nights, Start_Date=start, End_Date=end)
        new_guest.save()
        return redirect("guests:recordsview")
    return render(request, "guests/standardguest3.html")

def standard4(request):

guests/templates/guests/activeguests.html
{% extends "index/home.html" %}

{% load static %}

{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>
<style>

.table{
    overflow-y: auto;
    max-width: 100%;
    padding: 21px 0px 0px 20px;
    @media screen and (max-width) {
        background-color: white;
    }
}

table[id="table"], th, td{
    border: 1px solid black;
    text-transform: capitalize;
    border-collapse: collapse !important;
    padding: 4px;
    font-family:'Times New Roman', Times, serif;
    text-align:center;
}

table[id="table"] tr th{
    text-align: center;
    background-color: rgba(142,91,34,1);
    color: white;
    border-left: 1px solid white;
    border-right: 1px solid white;
}

table[id="table"] th[id="no"]{
    
    border-left: 1px solid rgba(142,91,34,1) !important;
    
    
}

table[id="table"] th[id="non"]{
    
    border-right: 1px solid rgba(142,91,34,1) !important;
    
}

table[id="table"] td[id="small"]{
    
    text-transform: lowercase;
    
}

</style>

</head>
<div class="table">
    
    <table id="table">
        <tr>
            
            <th id="no">S/N</th>
            <th>Name</th>
            <th>Email</th>
            <th>Occupation</th>
            <th>Room Category</th>
            <th>Room Type</th>
            <th>Room Number</th>
            <th>Amount Paid</th>
            <th>Number of Nights</th>
            <th>Start Date</th>
            <th id="non">End date</th>
        </tr>
        {% for guests in guest %}
        <tr>
            <td style="background-color: rgba(142,91,34,1); color:white"><b>{{forloop.counter}}</b></td>
            <td>{{guests.Name}}</td>
            <td id="small">{{guests.Email}}</td>
            <td>{{guests.Occupation}}</td>
            <td>{{guests.Room_Category}}</td>
            <td>{{guests.Room_Type}}</td>
            <td>{{guests.Room_Number}}</td>
            <td>{{guests.Amount_Paid}}</td>
            <td>{{guests.Number_of_Nights}}</td>
            <td>{{guests.Start_Date}}</td>
            <td>{{guests.End_Date}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
</html>

{% endblock body%}
    
    


    

guests/templates/guests/deluxeguest1.html
{% extends "index/home.html" %}

{% load static %}

{% block body%}
<!DOCTYPE html>
<html lang="en">
<head>
<style>

form[id="form"] {
    padding: 43px ;
    font-family:'Times New Roman', Times, serif
}

form[id="form"] fieldset[id="guest"] legend{
    margin-bottom: 5px;

}



form[id="form"] input[id="name"]{
    border: 1px solid black !important;
    
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 71px !important;

}

form[id="form"] input[id="email"]{
    border: 1px solid black !important;
   
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 70px !important;

}

form[id="form"] input[id="occupation"]{
    border: 1px solid black !important;
   
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 32px !important;

}


form[id="form"] fieldset[id="room"] legend{
    margin-bottom: 5px;

}

form[id="form"] fieldset[id="room"]{
    margin-top: 50px;

}



form[id="form"] input[id="roomcategory"]{
    border: 1px solid black !important;
    
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 40px !important;
    font-weight: 100;

}

form[id="form"] input[id="roomtype"]{
    border: 1px solid black !important;
   
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 70px !important;

}

form[id="form"] input[id="roomnumber"]{
    border: 1px solid black !important;
   
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 46px !important;

}

form[id="form"] fieldset[id="details"] legend{
    margin-bottom: 5px;

}

form[id="form"] fieldset[id="details"]{
    margin-top: 50px;

}

form[id="form"] input[id="amount"]{
    border: 1px solid black !important;
    
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 78px !important;
    font-weight: 100;

}

form[id="form"] input[id="start"]{
    border: 1px solid black !important;
   
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 98px !important;

}

form[id="form"] input[id="end"]{
    border: 1px solid black !important;
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 104px !important;
}

form[id="form"] input[id="nights"]{
    border: 1px solid black !important;
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 46px !important;
}


</style>
</head>
<div>
    <form id="form" action="{% url 'guests:deluxe1view' %}" method="post">
        {% csrf_token %}
        <fieldset id="guest">
            <legend >Guest Information</legend>
            <div style="border: 1px solid black; padding: 14px 0px 12px 10px">
                <label for="name"><b>Name:</b></label>
                <input type="text" name="Name" id="name" required><br>

                <label for="email"><b>Email:</b></label>
                <input type="email" name="Email" id="email" required><br>

                <label for="occupation"><b>Occupation:</b></label>
                <input type="text" name="Occupation" id="occupation" required><br>
                </div>
            
        </fieldset>
        
        <fieldset id="room">
            <legend>Room Information</legend>
            <div style="border: 1px solid black; padding: 14px 0px 12px 10px">
                <label for="roomcategory"><b>Room Category:</b></label>
                <input type="text" name="Room_Category" id="roomcategory" value="Deluxe" required><br>

                <label for="roomtype"><b>Room Type:</b></label>
                <input type="text" name="Room_Type" id="roomtype" value="King Size Bedroom" required><br>

                <label for="roomnumber"><b>Room Number:</b></label>
                <input type="text" name="Room_Number" id="roomnumber"><br>
            </div>
        </fieldset>
        
        
        <fieldset id="details">
            <legend>Room Detail</legend>
            <div style="border: 1px solid black; padding: 14px 0px 12px 10px">
                
                <label for="amount"><b>Amount Paid:</b></label>
                <input type="text" name="Amount_Paid" id="amount" maxlength="10"><br>
        
                <label for="nights"><b>Number of Nights:</b></label>
                <input type="number" name="Number_of_Nights" id="nights"><br>
        
                <label for="start"><b>Start Date:</b></label>
                <input type="date" name="Start_Date" id="start"><br>
        
                <label for="end"><b>End Date:</b></label>
                <input type="date" name="End_Date" id="end"><br>
            </div>
           
        </fieldset>
       
        <div style="padding: 14px 0px 12px 0px">
            <button type="submit" style="padding: 6px" validate >Submit</button>
        </div>
        
    </form>

</div>


</html>

{% endblock body%}
    
    


    

guests/templates/guests/deluxeguest2.html
{% extends "index/home.html" %}
{% load static %}

{% block body%}
<!DOCTYPE html>
<html lang="en">
<head>
<style>

form[id="form"] {
    padding: 43px ;
    font-family:'Times New Roman', Times, serif
}

form[id="form"] fieldset[id="guest"] legend{
    margin-bottom: 5px;

}



form[id="form"] input[id="name"]{
    border: 1px solid black !important;
    
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 71px !important;

}

form[id="form"] input[id="email"]{
    border: 1px solid black !important;
   
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 70px !important;

}

form[id="form"] input[id="occupation"]{
    border: 1px solid black !important;
   
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 32px !important;

}


form[id="form"] fieldset[id="room"] legend{
    margin-bottom: 5px;

}

form[id="form"] fieldset[id="room"]{
    margin-top: 50px;

}



form[id="form"] input[id="roomcategory"]{
    border: 1px solid black !important;
    
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 40px !important;
    font-weight: 100;

}

form[id="form"] input[id="roomtype"]{
    border: 1px solid black !important;
   
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 70px !important;

}

form[id="form"] input[id="roomnumber"]{
    border: 1px solid black !important;
   
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 46px !important;

}

form[id="form"] fieldset[id="details"] legend{
    margin-bottom: 5px;

}

form[id="form"] fieldset[id="details"]{
    margin-top: 50px;

}

form[id="form"] input[id="amount"]{
    border: 1px solid black !important;
    
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 78px !important;
    font-weight: 100;

}

form[id="form"] input[id="start"]{
    border: 1px solid black !important;
   
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 98px !important;

}

form[id="form"] input[id="end"]{
    border: 1px solid black !important;
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 104px !important;
}

form[id="form"] input[id="nights"]{
    border: 1px solid black !important;
    width: 350px !important;
    height: 25px !important;
    margin: -1002px 46px !important;
}


</style>
</head>
<div>
    <form id="form" action="{% url 'guests:deluxe2view' %}" method="post">
        {% csrf_token %}
        <fieldset id="guest">
            <legend >Guest Information</legend>
            <div style="border: 1px solid black; padding: 14px 0px 12px 10px">
                <label for="name"><b>Name:</b></label>
                <input type="text" name="Name" id="name" required><br>

                <label for="email"><b>Email:</b></label>
                <input type="email" name="Email" id="email" required><br>

                <label for="occupation"><b>Occupation:</b></label>
                <input type="text" name="Occupation" id="occupation" required><br>
                </div>
            
        </fieldset>
        
        <fieldset id="room">
            <legend>Room Information</legend>
            <div style="border: 1px solid black; padding: 14px 0px 12px 10px">
                <label for="roomcategory"><b>Room Category:</b></label>
                <input type="text" name="Room_Category" id="roomcategory" value="Deluxe" required><br>

                <label for="roomtype"><b>Room Type:</b></label>
                <input type="text" name="Room_Type" id="roomtype" value="Deluxe Room" required><br>

                <label for="roomnumber"><b>Room Number:</b></label>
                <input type="text" name="Room_Number" id="roomnumber"><br>
            </div>
        </fieldset>
        
        
        <fieldset id="details">
            <legend>Room Detail</legend>
            <div style="border: 1px solid black; padding: 14px 0px 12px 10px">
                
                <label for="amount"><b>Amount Paid:</b></label>
                <input type="text" name="Amount_Paid" id="amount" maxlength="10"><br>
        
                <label for="nights"><b>Number of Nights:</b></label>
                <input type="number" name="Number_of_Nights" id="nights"><br>
        
                <label for="start"><b>Start Date:</b></label>
                <input type="date" name="Start_Date" id="start"><br>
        
                <label for="end"><b>End Date:</b></label>
                <input type="date" name="End_Date" id="end"><br>
            </div>
           
        </fieldset>
       
        <div style="padding: 14px 0px 12px 0px">
            <button type="submit" style="padding: 6px">Submit</button>
        </div>
        
    </form>

</div>
</html>

{% endblock body%}
    
    


    

guests/templates/guests/record.html
{% extends "index/home.html" %}

{% load static %}


{% block body %}

<!DOCTYPE html>
<html>
<head>
<style>
a[id="new"]:hover{
    background-color: rgba(142,91,34,1);
    color: white !important;
    border: none !important;
    text-decoration: none !important;
}


@media only screen and (max-width:768px) {
    div a[id="new"]{
        background-color: rgba(142,91,34,1);
        text-align: center;
        padding: 23px 120px !important;
        color: white !important
    }
        
}


@media only screen and (min-width:768px) and (max-width:1200px) {
    div a[id="new"]{
        background-color: rgba(142,91,34,1);
        text-align: center;
        padding: 23px 190px !important;
        color: white !important
    }
        
}





@media only screen and (max-width:1700px) and (min-width: 1200px) {
    div a[id="new"]{
        background-color: rgba(142,91,34,1);
        text-align: center;
        padding: 24px 400px !important;
        color: white !important
    }
        
}

</style>

</head>

<div style="text-align: center; font-size: 25px; margin: 30px 0px -20px 0px; font-family:'Times New Roman', Times, serif;">
    This page is designed for the Management of <b>XYZ-Hotel</b> and to be accessed only by the Admin or Recieptionist and Management of XYZ-Hotel itself.<br><br><b>Note:</b><br><b>1. </b>To manage a room for a guest, choose a room based on the guests choice.<br><b>2. </b>Some modifications would be made over time on this website 
    
</div>
   
<div style="margin-left: 120px; padding-bottom: 0px;">
    <div style="margin-top: 100px; margin-left: 60px; padding-bottom: 200px;">
        <a id="new" href="{% url 'index:manageview' %}" style="font-family: 'Times New Roman', Times, serif; border: 1px solid; color: rgba(142,91,34,1);" > MANAGE NEW GUESTS</a>
    </div>
    
    <div style="margin-top: -134px; margin-left: 60px; padding-bottom: 200px;">
        <a id="new" href="{% url 'guests:activeguestsview' %}" style="font-family: 'Times New Roman', Times, serif;border: 1px solid; color: rgba(142,91,34,1);"> VIEW GUESTS RECORD</a>
    </div>
    
    
    <!--<div style="margin-top: -225px; margin-left: 580px; padding-bottom: 200px;">
        <a id="new" href="{% url 'index:manageview' %}" style="font-family: 'Times New Roman', Times, serif;border: 1px solid; color: rgba(142,91,34,1); padding: 24px;"> INACTIVE GUESTS</a>
    </div>
    
    <div  style="margin-top: -310px;  margin-left: 860px; padding-bottom: 200px;">
        <a id="new" href="{% url 'index:manageview' %}" style="font-family: 'Times New Roman', Times, serif;border: 1px solid; color: rgba(142,91,34,1); padding: 24px;"> SETTLED AND GONE GUESTS </a>
    </div>-->
</div>


</html>
{% endblock body %}

guests/templates/guests/todelete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

<style>
a[id="new"]:hover{
    background-color: rgba(142,91,34,1);
    color: white !important;
    border: none !important;
    text-decoration: none !important;
}




@media only screen and (max-width:500px) {
    div a{
        background-color: black;
    }
        
}
</style>

</head>
<body>
<div style="text-align: center; font-size: 25px; margin: 30px 0px -20px 0px; font-family:'Times New Roman', Times, serif;">
    This page is designed for the Management of <b>XYZ-Hotel</b> and to be accessed only by the Admin or Recieptionist and Management of XYZ-Hotel itself.<br><br><b>Note:</b><br><b>1. </b>To manage a room for a guest, choose a room based on the guests choice.<br><b>2. </b>Some modifications would be made over time on this website 
    
</div>
   
<div style="margin-left: 120px; padding-bottom: 0px;">
    <div style="margin-top: 100px; margin-left: 60px; padding-bottom: 200px;">
        <a id="new" href="{% url 'index:manageview' %}" style="font-family: 'Times New Roman', Times, serif; border: 1px solid; color: rgba(142,91,34,1); padding: 24px 400px;" > MANAGE A NEW GUEST</a>
    </div>
    
    <div style="margin-top: -134px; margin-left: 60px; padding-bottom: 200px;">
        <a id="new" href="{% url 'guests:activeguestsview' %}" style="font-family: 'Times New Roman', Times, serif;border: 1px solid; color: rgba(142,91,34,1); padding: 24px 403px;"> VIEW GUESTS RECORD</a>
    </div>
    
    
    <!--<div style="margin-top: -225px; margin-left: 580px; padding-bottom: 200px;">
        <a id="new" href="{% url 'index:manageview' %}" style="font-family: 'Times New Roman', Times, serif;border: 1px solid; color: rgba(142,91,34,1); padding: 24px;"> INACTIVE GUESTS</a>
    </div>
    
    <div  style="margin-top: -310px;  margin-left: 860px; padding-bottom: 200px;">
        <a id="new" href="{% url 'index:manageview' %}" style="font-family: 'Times New Roman', Times, serif;border: 1px solid; color: rgba(142,91,34,1); padding: 24px;"> SETTLED AND GONE GUESTS </a>
    </div>-->
</div>


</body>
</html>